from ._ground_site import GroundSite

_GROUND_SITES_LIST: list[GroundSite] = [
    GroundSite(
        name="TROPOS",
        long_name="TROPOS (LPZ)",
        aliases=["tropos"],
        latitude=51.352757,
        longitude=12.43392,
        altitude=125.0,
        cloudnet_name="leipzig",
    ),
    GroundSite(
        name="Leipzig",
        long_name="Leipzig (GER)",
        aliases=["leipzig", "lpz"],
        latitude=51.352757,
        longitude=12.43392,
        altitude=125.0,
        cloudnet_name="leipzig",
    ),
    GroundSite(
        name="Mindelo",
        long_name="Mindelo (CPV)",
        aliases=["mindelo", "cpv"],
        latitude=16.878,
        longitude=-24.995,
        altitude=13.0,
        cloudnet_name="mindelo",
    ),
    GroundSite(
        name="Dushanbe",
        long_name="Dushanbe (TJK)",
        aliases=["dushanbe", "tjk"],
        latitude=38.559,
        longitude=68.856,
        altitude=864.0,
        cloudnet_name="dushanbe",
    ),
    GroundSite(
        name="Melpitz",
        long_name="Melpitz (GER)",
        aliases=["melpitz"],
        latitude=51.526,
        longitude=12.928,
        altitude=83.0,
        cloudnet_name="melpitz",
    ),
    GroundSite(
        name="Limassol",
        long_name="Limassol (CYP)",
        aliases=["limassol", "cyp", "cyprus"],
        latitude=34.67667,
        longitude=33.04417,
        altitude=3.0,
        cloudnet_name="limassol",
    ),
    GroundSite(
        name="Antikythera",
        long_name="Antikythera (GRC)",
        aliases=["antikythera", "grc", "greece"],
        latitude=35.86,
        longitude=23.31,
        altitude=193.0,
        cloudnet_name="antikythera",
    ),
    GroundSite(
        name="Evora",
        long_name="Evora (PRT)",
        aliases=["evora", "prt", "portugal"],
        latitude=38.576,
        longitude=-7.911,
        altitude=290.0,
        cloudnet_name="evora",
    ),
    GroundSite(
        name="HPB",
        long_name="Hohenpeissenberg (GER)",
        aliases=["hpb", "hohenpeissenberg"],
        latitude=47.801473,
        longitude=11.009348,
        altitude=990.0,
        cloudnet_name="hpb",
    ),
    GroundSite(
        name="Warsaw",
        long_name="Warsaw (POL)",
        aliases=["warsaw", "pol", "poland"],
        latitude=52.233608,
        longitude=21.020265,
        altitude=113.0,
        cloudnet_name="warsaw",
    ),
    GroundSite(
        name="Kuopio",
        long_name="Kuopio (FIN)",
        aliases=["kuopio", "fin", "finland"],
        latitude=62.965698,
        longitude=27.666004,
        altitude=78.0,
        cloudnet_name="kuopio",
    ),
    GroundSite(
        name="Cabauw",
        long_name="Cabauw (NL)",
        aliases=["cabauw", "nl", "netherlands"],
        latitude=51.9677,
        longitude=4.9271,
        altitude=0.0,
    ),
    GroundSite(
        name="Koganei",
        long_name="Koganei (JP)",
        aliases=["koganei", "jp", "japan"],
        latitude=35.7,
        longitude=139.48,
        altitude=70.0,
    ),
    GroundSite(
        name="Neumayer III",
        long_name="Neumayer-Station III",
        aliases=["neumayer", "neumayer3", "neumayeriii"],
        latitude=-70.674444,
        longitude=-8.274167,
        altitude=41.0,
    ),
    GroundSite(
        name="Invercargill",
        long_name="Invercargill (NZ)",
        aliases=["invercargill", "gosouth"],
        latitude=-46.40000153,
        longitude=168.3000031,
        altitude=20.0,
    ),
    GroundSite(
        name="Lindenberg",
        long_name="Lindenberg (GER)",
        aliases=["lindenberg", "mol", "rao"],
        latitude=52.208,
        longitude=14.118,
        altitude=118.0,
    ),
    GroundSite(
        name="Pallas",
        long_name="Pallas (FIN)",
        aliases=["pallas"],
        latitude=67.988,
        longitude=24.243,
        altitude=354.0,
    ),
    GroundSite(
        name="Tsukuba",
        long_name="Tsukuba (JP)",
        aliases=["tsukuba"],
        latitude=36.05,
        longitude=140.12,
        altitude=30.0,
    ),
    GroundSite(
        name="Falkenberg",
        long_name="Falkenberg (GER)",
        aliases=["falkenberg"],
        latitude=52.167045,
        longitude=14.121741,
        altitude=71.0,
    ),
]
