from typing import Literal, TypeAlias

from ._site import Site

SiteLike: TypeAlias = (
    Site
    | Literal[
        "tropos",
        "leipzig",
        "mindelo",
        "dushanbe",
        "melpitz",
        "limassol",
        "antikythera",
        "evora",
        "hpb",
        "warsaw",
        "kuopio",
        "cabauw",
        "koganei",
        "neumayer",
        "invercargill",
        "lindenberg",
        "pallas",
        "tsukuba",
        "falkenberg",
        "munich",
        "palaiseau",
        "bucharest",
        "galati",
        "juelich",
        "lampedusa",
        "granada",
        "payerne",
        "laquila",
        "potenza",
        "chilbolton",
        "hyytiala",
        "lim",
        "cluj",
        "nyalesund",
        "maido",
        "attocampina",
    ]
    | str
)

_SITE_LIST: list[Site] = [
    Site(
        name="TROPOS",
        long_name="TROPOS, Leipzig (DE)",
        aliases=["tropos"],
        latitude=51.352757,
        longitude=12.43392,
        altitude=125.0,
        cloudnet_name="leipzig",
    ),
    Site(
        name="Leipzig",
        long_name="Leipzig (DE)",
        aliases=["leipzig", "lpz"],
        latitude=51.352757,
        longitude=12.43392,
        altitude=125.0,
        cloudnet_name="leipzig",
    ),
    Site(
        name="Mindelo",
        long_name="Mindelo (CV)",
        aliases=["mindelo", "cpv"],
        latitude=16.878,
        longitude=-24.995,
        altitude=13.0,
        cloudnet_name="mindelo",
    ),
    Site(
        name="Dushanbe",
        long_name="Dushanbe (TJK)",
        aliases=["dushanbe", "tjk"],
        latitude=38.559,
        longitude=68.856,
        altitude=864.0,
        cloudnet_name="dushanbe",
    ),
    Site(
        name="Melpitz",
        long_name="Melpitz (DE)",
        aliases=["melpitz"],
        latitude=51.526,
        longitude=12.928,
        altitude=83.0,
        cloudnet_name="melpitz",
    ),
    Site(
        name="Limassol",
        long_name="Limassol (CY)",
        aliases=["limassol", "cyp", "cyprus"],
        latitude=34.67667,
        longitude=33.04417,
        altitude=3.0,
        cloudnet_name="limassol",
    ),
    Site(
        name="Antikythera",
        long_name="Antikythera (GR)",
        aliases=["antikythera", "grc", "greece"],
        latitude=35.86,
        longitude=23.31,
        altitude=193.0,
        cloudnet_name="antikythera",
    ),
    Site(
        name="Evora",
        long_name="Evora (PT)",
        aliases=["evora", "prt", "portugal"],
        latitude=38.576,
        longitude=-7.911,
        altitude=290.0,
        cloudnet_name="evora",
    ),
    Site(
        name="HPB",
        long_name="Hohenpeissenberg (DE)",
        aliases=["hpb", "hohenpeissenberg"],
        latitude=47.801473,
        longitude=11.009348,
        altitude=990.0,
        cloudnet_name="hpb",
    ),
    Site(
        name="Warsaw",
        long_name="Warsaw (PL)",
        aliases=["warsaw", "pol", "poland"],
        latitude=52.233608,
        longitude=21.020265,
        altitude=113.0,
        cloudnet_name="warsaw",
    ),
    Site(
        name="Kuopio",
        long_name="Kuopio (FI)",
        aliases=["kuopio", "fin", "finland"],
        latitude=62.965698,
        longitude=27.666004,
        altitude=78.0,
        cloudnet_name="kuopio",
    ),
    Site(
        name="Cabauw",
        long_name="Cabauw (NL)",
        aliases=["cabauw", "nl", "netherlands"],
        latitude=51.9677,
        longitude=4.9271,
        altitude=0.0,
    ),
    Site(
        name="Koganei",
        long_name="Koganei (JP)",
        aliases=["koganei", "jp", "japan"],
        latitude=35.7,
        longitude=139.48,
        altitude=70.0,
    ),
    Site(
        name="Neumayer III",
        long_name="Neumayer-Station III",
        aliases=["neumayer", "neumayer3", "neumayeriii"],
        latitude=-70.674444,
        longitude=-8.274167,
        altitude=41.0,
    ),
    Site(
        name="Invercargill",
        long_name="Invercargill (NZ)",
        aliases=["invercargill", "gosouth"],
        latitude=-46.40000153,
        longitude=168.3000031,
        altitude=20.0,
    ),
    Site(
        name="Lindenberg",
        long_name="Lindenberg (DE)",
        aliases=["lindenberg", "mol", "rao"],
        latitude=52.208,
        longitude=14.118,
        altitude=118.0,
    ),
    Site(
        name="Pallas",
        long_name="Pallas (FI)",
        aliases=["pallas"],
        latitude=67.988,
        longitude=24.243,
        altitude=354.0,
    ),
    Site(
        name="Tsukuba",
        long_name="Tsukuba (JP)",
        aliases=["tsukuba"],
        latitude=36.05,
        longitude=140.12,
        altitude=30.0,
    ),
    Site(
        name="Falkenberg",
        long_name="Falkenberg (DE)",
        aliases=["falkenberg"],
        latitude=52.167045,
        longitude=14.121741,
        altitude=71.0,
    ),
    Site(
        name="Munich",
        long_name="Munich (DE)",
        aliases=["munich"],
        latitude=48.148,
        longitude=11.573,
        altitude=538.0,
    ),
    Site(
        name="Palaiseau",
        long_name="Palaiseau (FR)",
        aliases=["palaiseau"],
        latitude=48.717,
        longitude=2.209,
        altitude=156.0,
    ),
    Site(
        name="Bucharest",
        long_name="Bucharest (RO)",
        aliases=["bucharest"],
        latitude=44.344,
        longitude=26.012,
        altitude=77.0,
    ),
    Site(
        name="Galati",
        long_name="Galati (RO)",
        aliases=["galati"],
        latitude=45.435,
        longitude=28.037,
        altitude=40.0,
    ),
    Site(
        name="Juelich",
        long_name="Juelich (DE)",
        aliases=["juelich", "jülich"],
        latitude=50.908,
        longitude=6.413,
        altitude=111.0,
    ),
    Site(
        name="Lampedusa",
        long_name="Lampedusa (IT)",
        aliases=["lampedusa"],
        latitude=35.5183,
        longitude=12.6303,
        altitude=45.0,
    ),
    Site(
        name="Granada",
        long_name="Granada (ES)",
        aliases=["granada"],
        latitude=37.164,
        longitude=-3.605,
        altitude=680.0,
    ),
    Site(
        name="Payerne",
        long_name="Payerne (CH)",
        aliases=["payerne"],
        latitude=46.813,
        longitude=6.944,
        altitude=491.0,
    ),
    Site(
        name="L'Aquila",
        long_name="L'Aquila (IT)",
        aliases=["laquila"],
        latitude=42.383,
        longitude=13.315,
        altitude=683.0,
    ),
    Site(
        name="Potenza",
        long_name="Potenza (IT)",
        aliases=["potenza"],
        latitude=40.601,
        longitude=15.724,
        altitude=760.0,
    ),
    Site(
        name="Chilbolton",
        long_name="Chilbolton (GB-ENG)",
        aliases=["chilbolton"],
        latitude=51.144,
        longitude=-1.439,
        altitude=85.0,
    ),
    Site(
        name="Hyytiala",
        long_name="Hyytiälä (FI)",
        aliases=["hyytiala"],
        latitude=61.844,
        longitude=24.287,
        altitude=150.0,
    ),
    Site(
        name="LIM",
        long_name="LIM, Leipzig (DE)",
        aliases=["lim", "leipziglim"],
        latitude=51.333,
        longitude=12.389,
        altitude=126.0,
    ),
    Site(
        name="Cluj",
        long_name="Cluj-Napoca (RO)",
        aliases=["cluj", "clujnapoca"],
        latitude=46.7678,
        longitude=23.54006,
        altitude=459.0,
    ),
    Site(
        name="Ny-Alesund",
        long_name="Ny-Alesund (NO)",
        aliases=["nyalesund", "newalesund"],
        latitude=78.923,
        longitude=11.922,
        altitude=19.0,
    ),
    Site(
        name="Maido",
        long_name="Maido (RE)",
        aliases=["maido"],
        latitude=-21.079,
        longitude=55.383,
        altitude=2200.0,
    ),
    Site(
        name="ATTO-Campina",
        long_name="ATTO-Campina (BR)",
        aliases=["attocampina", "campina"],
        latitude=-2.181583,
        longitude=-59.021861,
        altitude=30.0,
    ),
]
