from typing import Any


def get_default_properties_dict() -> dict[str, dict[str, Any]]:
    return {
        "EarthCAREAuxiliary_MAAP": {
            "product:type": {
                "enum": [
                    "AUX_CCAM_A",
                    "AUX_CCAR_A",
                    "AUX_CCAX_A",
                    "AUX_CCDC_A",
                    "AUX_CCER_B",
                    "AUX_CCGT_B",
                    "AUX_CCIA_A",
                    "AUX_CCIA_B",
                    "AUX_CCIA_M",
                    "AUX_CCLI_B",
                    "AUX_CCMC_A",
                    "AUX_CCOG_A",
                    "AUX_CCOG_B",
                    "AUX_CCPS_A",
                    "AUX_CCPS_B",
                    "AUX_CCPS_M",
                    "AUX_CCSN_B",
                    "AUX_CCSX_A",
                    "AUX_CSMO_M",
                    "AUX_ORBPRE",
                    "AUX_ORBRES",
                    "AUX_STAT_M",
                    "AUX_TBBL_M",
                    "AUX_TSCO_M",
                    "AUX_VRAD_M",
                    "BBR_SOL_1B",
                    "GEO_ATTOBS",
                    "GEO_ORBOBS",
                ]
            },
            "version": {},
            "sat:absolute_orbit": {},
            "frame": {},
        },
        "EarthCAREOrbitData_MAAP": {
            "product:type": {"enum": ["AUX_ORBPRE", "GEO_ATTOBS", "GEO_ORBOBS", "MPL_ORBSCT"]},
            "version": {},
            "frame": {},
        },
        "JAXAL2Validated_MAAP": {
            "product:type": {
                "enum": [
                    "ACM_CLP_2B",
                    "AC__CLP_2B",
                    "ALL_RAD_2B",
                    "ATL_CLA_2A",
                    "CPR_CLP_2A",
                    "CPR_ECO_2A",
                    "MSI_CLP_2A",
                ]
            },
            "sat:orbit_state": {"enum": ["ASCENDING", "DESCENDING"]},
            "version": {},
            "sat:absolute_orbit": {},
            "frame": {},
        },
        "EarthCAREL2Validated_MAAP": {
            "product:type": {
                "enum": [
                    "ACM_CAP_2B",
                    "ACM_COM_2B",
                    "ACM_RT__2B",
                    "AC__TC__2B",
                    "ALL_3D__2B",
                    "ALL_DF__2B",
                    "AM__ACD_2B",
                    "AM__CTH_2B",
                    "ATL_AER_2A",
                    "ATL_ALD_2A",
                    "ATL_CLA_2A",
                    "ATL_CTH_2A",
                    "ATL_EBD_2A",
                    "ATL_FM__2A",
                    "ATL_ICE_2A",
                    "ATL_TC__2A",
                    "BMA_FLX_2B",
                    "BM__RAD_2B",
                    "CPR_CD__2A",
                    "CPR_CLD_2A",
                    "CPR_FMR_2A",
                    "CPR_TC__2A",
                    "MSI_AOT_2A",
                    "MSI_CM__2A",
                    "MSI_COP_2A",
                ]
            },
            "sat:orbit_state": {"enum": ["ASCENDING", "DESCENDING"]},
            "version": {},
            "sat:absolute_orbit": {},
            "frame": {},
        },
        "EarthCAREL2Products_MAAP": {
            "product:type": {
                "enum": [
                    "ACM_CAP_2B",
                    "ACM_COM_2B",
                    "ACM_RT__2B",
                    "AC__TC__2B",
                    "ALL_3D__2B",
                    "ALL_DF__2B",
                    "AM__ACD_2B",
                    "AM__CTH_2B",
                    "ATL_AER_2A",
                    "ATL_ALD_2A",
                    "ATL_CLA_2A",
                    "ATL_CTH_2A",
                    "ATL_EBD_2A",
                    "ATL_FM__2A",
                    "ATL_ICE_2A",
                    "ATL_TC__2A",
                    "BMA_FLX_2B",
                    "BM__RAD_2B",
                    "CPR_APC_2A",
                    "CPR_CD__2A",
                    "CPR_CLD_2A",
                    "CPR_FMR_2A",
                    "CPR_TC__2A",
                    "MSI_AOT_2A",
                    "MSI_CM__2A",
                    "MSI_COP_2A",
                ]
            },
            "sat:orbit_state": {"enum": ["ASCENDING", "DESCENDING"]},
            "version": {},
            "sat:absolute_orbit": {},
            "frame": {},
        },
        "JAXAL2InstChecked_MAAP": {
            "product:type": {
                "enum": [
                    "ACM_CLP_2B",
                    "AC__CLP_2B",
                    "ALL_RAD_2B",
                    "ATL_CLA_2A",
                    "CPR_CLP_2A",
                    "CPR_ECO_2A",
                    "MSI_CLP_2A",
                ]
            },
            "sat:orbit_state": {"enum": ["ASCENDING", "DESCENDING"]},
            "version": {},
            "sat:absolute_orbit": {},
            "frame": {},
        },
        "JAXAL2Products_MAAP": {
            "product:type": {
                "enum": [
                    "ACM_CLP_2B",
                    "AC__CLP_2B",
                    "ALL_RAD_2B",
                    "ATL_CLA_2A",
                    "CPR_CLP_2A",
                    "CPR_ECO_2A",
                    "MSI_CLP_2A",
                ]
            },
            "version": {},
            "sat:orbit_state": {"enum": ["ASCENDING", "DESCENDING"]},
            "sat:absolute_orbit": {},
            "frame": {},
        },
        "EarthCAREL2InstChecked_MAAP": {
            "product:type": {
                "enum": [
                    "ACM_CAP_2B",
                    "ACM_COM_2B",
                    "ACM_RT__2B",
                    "AC__TC__2B",
                    "ALL_3D__2B",
                    "ALL_DF__2B",
                    "AM__ACD_2B",
                    "AM__CTH_2B",
                    "ATL_AER_2A",
                    "ATL_ALD_2A",
                    "ATL_CLA_2A",
                    "ATL_CTH_2A",
                    "ATL_EBD_2A",
                    "ATL_FM__2A",
                    "ATL_ICE_2A",
                    "ATL_TC__2A",
                    "AUX_CCOG_A",
                    "AUX_CCPS_A",
                    "BMA_FLX_2B",
                    "BM__RAD_2B",
                    "CPR_APC_2A",
                    "CPR_CD__2A",
                    "CPR_CLD_2A",
                    "CPR_FMR_2A",
                    "CPR_TC__2A",
                    "MSI_AOT_2A",
                    "MSI_CM__2A",
                    "MSI_COP_2A",
                ]
            },
            "sat:orbit_state": {"enum": ["ASCENDING", "DESCENDING"]},
            "version": {},
            "sat:absolute_orbit": {},
            "frame": {},
        },
        "EarthCAREL1InstChecked_MAAP": {
            "product:type": {
                "enum": [
                    "ATL_CSC_1B",
                    "ATL_DCC_1B",
                    "ATL_FSC_1B",
                    "ATL_NOM_1B",
                    "AUX_JSG_1D",
                    "AUX_MET_1D",
                    "BBR_LIN_1B",
                    "BBR_NOM_1B",
                    "BBR_SNG_1B",
                    "CPR_NOM_1B",
                    "MSI_BBS_1B",
                    "MSI_NOM_1B",
                    "MSI_RGR_1C",
                ]
            },
            "sat:orbit_state": {"enum": ["ASCENDING", "DESCENDING"]},
            "version": {},
            "sat:absolute_orbit": {},
            "frame": {},
        },
        "EarthCAREL0L1Products_MAAP": {
            "product:type": {
                "enum": [
                    "ATL_CSC_1B",
                    "ATL_DCC_1B",
                    "ATL_FSC_1B",
                    "ATL_NOM_0_",
                    "ATL_NOM_1B",
                    "AUX_JSG_1D",
                    "AUX_MET_1D",
                    "BBR_LIN_1B",
                    "BBR_NOM_0_",
                    "BBR_NOM_1B",
                    "BBR_SNG_1B",
                    "BBR_SOL_1B",
                    "CPR_NOM_1B",
                    "MSI_BBS_1B",
                    "MSI_DRK_1B",
                    "MSI_NOM_0_",
                    "MSI_NOM_1B",
                    "MSI_RGR_1C",
                    "MSI_SD1_1B",
                    "MSI_SD2_1B",
                    "MSI_TRF_1B",
                    "TLM_NOM_0_",
                ]
            },
            "sat:orbit_state": {"enum": ["ASCENDING", "DESCENDING"]},
            "version": {},
            "sat:absolute_orbit": {},
            "frame": {},
        },
        "EarthCAREXMETL1DProducts10_MAAP": {
            "product:type": {"enum": ["AUX_MET_1D"]},
            "version": {},
            "sat:absolute_orbit": {},
            "frame": {},
        },
        "EarthCAREL1Validated_MAAP": {
            "product:type": {
                "enum": [
                    "ATL_NOM_1B",
                    "AUX_JSG_1D",
                    "BBR_NOM_1B",
                    "BBR_SNG_1B",
                    "CPR_NOM_1B",
                    "MSI_NOM_1B",
                    "MSI_RGR_1C",
                ]
            },
            "sat:orbit_state": {"enum": ["ASCENDING", "DESCENDING"]},
            "version": {},
            "sat:absolute_orbit": {},
            "frame": {},
        },
    }
